#ifndef _SEARCHOPTIONS_H
#define _SEARCHOPTIONS_H

#define SEARCHFLAG_CASESENSITIVE	 1

#define SEARCHFLAG_STARTONLY		 4

#define SEARCHFLAG_INCLUDEPATH		 2
#define SEARCHFLAG_INCLUDEFILENAME   8
#define SEARCHFLAG_INCLUDEINDEX     16
#define SEARCHFLAG_INCLUDEVIEW      32
#define SEARCHFLAG_INCLUDEWILDCARD  64

enum SortOrder
{
	NONE			= -2,
	ALWAYSREMEMBER	= -1,
	FILENAME		= 0,
	PATH			= 1,
	INDEX			= 2
};

#endif