
#ifndef _SEARCHOPTIONS_H
#define _SEARCHOPTIONS_H

#define SEARCHFLAG_CASESENSITIVE	 1

#define SEARCHFLAG_STARTONLY		 4

#define SEARCHFLAG_INCLUDEPATH		 2
#define SEARCHFLAG_INCLUDEFILENAME   8
#define SEARCHFLAG_INCLUDEINDEX     16

#define REVERSE_SORT_ORDER      0x8000

enum SortOrder
{
	ALWAYSREMEMBER,
	FILENAME,
	PATH,
	INDEX
};


#endif